### PR TITLE
Update data/ForC_measurements.csv

### PR DESCRIPTION
**Pull request by mcgregorian1**
Finished updating Chave_2008 data

### CODE REVIEW

**Comment by mcgregorian1** [comment]
I'm not sure why it can't be merged?

**Comment by teixeirak** [comment]
It looks like @ValentineHerr deleted the tropical.extratropical field. Please do that in yours/ verify that it otherwise matches, and try again. Another option could be to do a fresh download of what's there now and paste your changes to the end.

**Comment by mcgregorian1** [comment]
I hope I didn't make this more complicated. Currently the file is changed to have my data and the deleted tropical.extratropical field.

I ended up doing a separate commit (as opposed to a pull request) and it appears to have gone straight to the master. I did this because github desktop told me I hadn't committed anything from yesterday, but it seems to be fixed now. Can you please double check? The last entry on the csv should 17591.

**Comment by teixeirak** [comment]
That did not work.

**Pull request closed without merging**
