### PR TITLE
Beckybanbury

### PR DESCRIPTION
**Pull request by beckybanbury**

### CODE REVIEW

**Comment by teixeirak** [comment]
Looks great, thanks! I think there are a couple small issues that will be easier for me to review/correct once merged.

**Comment by teixeirak** [comment]
I made some changes in [this commit](https://github.com/forc-db/ForC/commit/e401e1e645ebede572cf8f8985b79080874005a1). Please review so that you know what needed changing, and fix the two items where I had to replace your entries with "NAC". It would be good for @mcgregorian1 to review as well.  I tried to update the metadata file as needed to clarify things that didn't make sense.
It seems a main thing to look out for is keeping units and data format in strict conformation to the formats defined in metadata, but otherwise looks great!

**Comment by mcgregorian1** [comment]
@teixeirak did you want retroactive application of the confidence interval change? As in, did you want the Chave_2008 full intervals to be added in the notes? Currently I only put the upper bound for those sites.

**Comment by teixeirak** [comment]
It's not critical to go back and get it, although it may be useful to put it in the notes. The handling of 95%CI isn't well configured in this database, but we're not using it now.

**Pull request merged**
